from ApFlashVulnerableChecker import analyze_logs
from datetime import datetime

# Directory containing AP logs
log_dir = r"data\2026\03\05\RUN_test"

# Run vulnerability checker
rows, summary = analyze_logs(log_dir)

# Output file
output_file = "vulnerable_AP_report.txt"

with open(output_file, "w", encoding="utf-8") as f:

    f.write("=========== AP FLASH VULNERABILITY REPORT ===========\n")
    f.write(f"Generated: {datetime.now()}\n")
    f.write(f"Source Directory: {log_dir}\n")
    f.write("=====================================================\n\n")

    if not rows:
        f.write("No vulnerable APs detected.\n")

    else:
        # Table header
        header = f"{'AP Name':25}{'Model':12}{'IP Address':18}{'Recovery Action'}\n"
        f.write(header)
        f.write("-" * 80 + "\n")

        # Print each vulnerable AP
        for r in rows:
            line = f"{r['ap_name']:25}{r['ap_model']:12}{r['ap_ip']:18}{r['recovery']}\n"
            f.write(line)

print("Clean vulnerability report written to:", output_file)
print("Summary file generated by parser:", summary)